### ISSUE TITLE
Service Temporarily Down

### ISSUE THREAD

**Issue by wlgrayjr** [Atomicorp/gvm#10]
When trying to run a task after the latest update, getting Error: Service Temporarily Down.

What could be causing this error?

**Comment by jacobamey** [comment]
I've seen this as well when running decent sized scans. /24 or bigger. Or when canceling a scan. 

I believe this to be primarily with the openvas-scanner its self but cannot confirm yet. My only recourse is to reboot the server as a `systemctl restart openvas-scanner` hangs indefinitely.

**Comment by atomicturtle** [comment]
Could be gvmd (formerly openvas-manager) that needs a restart too
