### ISSUE TITLE
Package update from OpenVAS to GVM breaks install

### ISSUE THREAD

**Issue by CipherMonger** [Atomicorp/gvm#11]
When running an update of packages on my CentOS 7 install, the openvas to gvm package replacements cause my install to no longer work.

A tail of /var/log/gvm/gsad.log shows the following:
`gsad main:MESSAGE:2019-04-19 14h05.36 utc:9587: Starting GSAD version 8.0.0
gsad main:CRITICAL:2019-04-19 14h05.36 utc:9588: main: Could not load private SSL key from /var/lib/gvm/private/CA/serverkey.pem: Failed to open file “/var/lib/gvm/private/CA/serverkey.pem”: No such file or directory`

Checking /var/lib/gvm, I have a single directory called "mgr", which is empty.

**Comment by atomicturtle** [comment]
Did you run openvas-setup?

**Comment by CipherMonger** [comment]
I just ran that and rebooted the server. The web interface is still unavailable, but the gsad.log no longer shows an error. Checking /var/lib/gvm, it looks like the file structure is there now.

Both the gsad and gvmd services are running, but a netstat shows nothing listening on port 9392.

**Comment by atomicturtle** [comment]
Check what port gsad is running on

**Comment by CipherMonger** [comment]
Ah ok, interesting: gsad is listening on http/6683 and https/6682, but only on IPv6. This device only has an IPv4 address.

**Comment by CipherMonger** [comment]
Anything further I can do to help unravel this? The openvas-setup command (and also gvm-setup) both still announce that it's supposed to be listening on 9392.

**Comment by atomicturtle** [comment]
Yeah, what happens when you do this on a clean image?

**Comment by CipherMonger** [comment]
After installing on a clean image, gsad is listening on HTTP & HTTPS, but still only on IPv6. Nothing is listening on 9392.

**Comment by Mb1984** [comment]
I'm in the same boat as CipherMonger aside from the fact that I cant get GSAD to start.
GVMD starts but does me no good.  No web page loads

**Comment by Mb1984** [comment]
I ran openvas-setu[ and it successfully ran through.
I now have GSAD and GVMD started but like CipherMonger.... No web page to display.

There are no error aside from  get_redis_ctx: redis connection error: No such file or directory  in the openvassd.log

**Comment by Mb1984** [comment]
I've now cleared the Redis error, I used the flush all. Everything starts up, no errors.... still not page display.

Whats going on ?

**Comment by Mb1984** [comment]
@CipherMonger   I dunno how it started working but I got it working.
I was where you were stuck, let me give you a few steps to check. I'm not sure what fixed my issue but hopefully itll help you

-yum uninstall gsad
-greenbone-nvt-sync ; openvasmd --rebuild
-openvas-setup     ....again
-sed -i '/^#.*unixsocket/s/^# //' /etc/redis.conf
-sudo redis-cli -s /var/run/redis/redis.sock flushall
-Rebooted into latest kernel installed  4.14 or 4.15  centos7
-ran this command     echo 'OPTIONS="--listen=0.0.0.0 --port=9392"' > /etc/sysconfig/gsad
-yum -y update && reboot

Not sure what step helped but give it a shot if you'd like. make a snapshot, I make no guarantee haha


Worth noting... I still cant get the Discovery tasks to run more than 1% but individual host scans work

**Comment by Mb1984** [comment]
Check your logs and your redis log

**Comment by CipherMonger** [comment]
After modifying /etc/sysconfig/gsad to include "--listen 0.0.0.0 --port=9392" and rebooting, I now have a functioning GUI, even though there are already separate lines for "GSA_ADDRESS=0.0.0.0" and "GSA_PORT=9392".

But, now that I have a functioning GUI, I see that all of my old data (targets, tasks, etc.) has been wiped out. Needless to say, that's kind of a problem.

**Comment by Martha-GitHub** [comment]
may be this helps https://github.com/greenbone/gvmd/blob/master/INSTALL.md ... look for the migrating section. (you can migrate the database)

**Comment by atomicturtle** [comment]
For pull requests the GSA project was just added here: https://github.com/Atomicorp/gsa/ note that this repo is being mirrored from our internal gitlab CI

**Comment by CipherMonger** [comment]
Finally got to a point where I could log into the GUI, but it was basically starting over from my 9.0.1 build:
* copied /etc/openvas/pwpolicy.conf to /etc/gvm/
* copied /etc/openvas/openvasmd_log.conf to /etc/gvm/gvmd_log.conf
* copied /var/lib/openvas/scap-data to /var/lib/gvm/scap-data
* copied /var/lib/openvas/cert-data to /var/lib/gvm/cert-data
* copied /var/lib/openvas/openvasmd to /var/lib/gvm/gvmd
* copied /var/lib/openvas/CA to /var/lib/gvm/CA
* copied /var/lib/openvas/private to /var/lib/gvm/private
* copied /var/lib/openvas/mgr/tasks.db to /var/lib/gvm/gvmd/gvmd.db

Installed IUS in order to get Python to a more recent build:
* yum -y install https://centos7.iuscommunity.org/ius-release.rpm

Ran a package upgrade
* yum updateinfo
* yum upgrade

Edited /etc/sysconfig/gsad to include "--listen 0.0.0.0 --port=9392"

Migrated database
* gvmd --migrate

Re-ran setup
* gvm-setup


However, at this point, it still seems like certain features don't work. If I go into a report and click on a vulnerability to expand it, then click the magnifying glass to the left of the vulnerability labeled "open all details", I get an error that reads "e.get_result.commands_response is undefined".

I also don't see a way to set overrides and notes on individual findings except by going to the global overrides or notes sections respectively. Maybe this is just part of the UI overhaul?

**Comment by atomicturtle** [comment]
closing this out since we're on 20.08 now
