### ISSUE TITLE
Rename greenbone-vulnerability-manager loader package to greenbone-vulnerability-management

### ISSUE THREAD

**Issue by cfi-gb** [Atomicorp/gvm#12]
Migrated from https://github.com/greenbone/gvm-libs/issues/197#issuecomment-484033864:
>> greenbone-vulnerability-manager (formerly openvas, our loader package for the whole suite)
>
> This could introduce some confusion for the following reason (because of the naming decision to go for GVM and GVMd which are differently):
>
> GVM = Greenbone Vulnerability Management (The projects "main" name, including e.g. openvas-scanner, gvmd, gvm-libs, ...)
> GVMd = Greenbone Vulnerability Manager daemon (The formerly openvas-manager, located now at https://github.com/greenbone/gvmd)

**Comment by atomicturtle** [comment]
Where I could, I kept with the name from the archive file:


openvas-libraries is now:  gvm-libs
openvas-manager is now: gvmd
openvas-cli is now: gvm-tools

These package names did not change:
openvas-scanner = openvas-scanner
greenbone-security-assistant(gsad) = greenbone-security-assistant 

And this project, while called "openvas" in github is packaged as  "gvm"

**Comment by cfi-gb** [comment]
@atomicturtle Basically i mean this: #27

GVM is "Greenbone Vulnerability Management" of which "gvmd" (the Greenbone Vulnerability Manager daemon) is part of.
