### ISSUE TITLE
Attempted update from 9.0.1. Cant start GSAD now. GVMD starts but no web page loads

### ISSUE THREAD

**Issue by Mb1984** [Atomicorp/gvm#13]
Upgrade to GVMD 10
Still cant get gsad to start
[root@openvas ~]# systemctl status gsad
● gsad.service - Greenbone Security Assistant (OpenVAS)
Loaded: loaded (/usr/lib/systemd/system/gsad.service; enabled; vendor preset: disabled)
Active: failed (Result: start-limit) since Mon 2019-04-29 23:37:52 EDT; 16min ago
Process: 6943 ExecStart=/usr/sbin/gsad $OPTIONS (code=exited, status=0/SUCCESS)
Main PID: 6946 (code=exited, status=1/FAILURE)
Apr 29 23:37:51 openvas. systemd[1]: Unit gsad.service entered failed state.
Apr 29 23:37:51 openvas. systemd[1]: gsad.service failed.
Apr 29 23:37:52 openvas. systemd[1]: gsad.service holdoff time over, scheduling restart.
Apr 29 23:37:52 openvas.systemd[1]: Stopped Greenbone Security Assistant (OpenVAS).
Apr 29 23:37:52 openvas. systemd[1]: start request repeated too quickly for gsad.service
Apr 29 23:37:52 openvas.systemd[1]: Failed to start Greenbone Security Assistant (OpenVAS).
Apr 29 23:37:52 openvassystemd[1]: Unit gsad.service entered failed state.
Apr 29 23:37:52 openvas. systemd[1]: gsad.service failed.
I get that GVMD replaces GSAD? right?
Well GVMD starts but I still cant get my weblink to load

**Comment by CipherMonger** [comment]
This looks similar to what I am running into, noted in issue #11

**Comment by atomicturtle** [comment]
closing this out as 20.08 is the current release
