### ISSUE TITLE
Starting and Stopping Openvas

### ISSUE THREAD

**Issue by wlgrayjr** [Atomicorp/gvm#14]
These are the commands I am currently using to start the application. 

gsad --http-sts --listen=X.X.X>X -p 9392 --gnutls-priorities="NORMAL:-VERS-TLS-ALL:+VERS-TLS1.2:-CIPHER-ALL:+AES-256-CBC" &
gvmd &
openvassd &

What are the commands to stop the application and restart? 

How do I kill a task that is not letting me edit scan configs?

Also do I still need gsad?  

Confused after upgrading and trying to find one place that has everything documented.

**Comment by atomicturtle** [comment]
out of date, 20.08 is the current release
