### ISSUE TITLE
Cant scan /24 range. Only a few IPs at a time after upgrading to gvmd openvas 10

### ISSUE THREAD

**Issue by Mb1984** [Atomicorp/gvm#16]
So, I finally got the latest version running.  Like others reported here, all tasks were wiped.

I moved all of the files and renamed as necessary such as tasks.db.  
I ran the database migration successfully (make sure to stop gvmd and redis to those stuck on this step).

However, the tasks still never appeared.  

Fine.... Ill recreate them.

Well, I've tried doing an immediate scan of 10.0.2.1-10.0.2.255.....Stuck at 1% for days.

Ive tried creating a Target List both manually and by uploading a file with all IPs then creating a Host Discovery task using the new Target List.... Stuck at 1% for days

I tried creating a Target List with say 5 IPs then just simply Running a Scan using the target list.... .This works.  So I can get it to work for say 5 IPs, but I cant get it to work for the whole block.

Any ideas on why?  Is there a host limitation set somewhere?  Is there a specific log you'd like me to post?

Thanks!

**Comment by cfi-gb** [comment]
@Mb1984 As this isn't a packaging issue its recommended to join https://community.greenbone.net

There you can find some notes on how to correctly configure redis to scan larger target ranges:

https://community.greenbone.net/t/scanning-subnets-results-in-1-hanging/2131/5
https://community.greenbone.net/t/hint-redis-setup-configuration-for-gse-gvm-openvas/333

**Comment by Mb1984** [comment]
Oh that was it. Thank you so much.
