### ISSUE TITLE
openvas-smb module not running

### ISSUE THREAD

**Issue by KyWill** [Atomicorp/gvm#17]
new install of greenbone vulnerability manager on centos 7 using atomic repo. able to authenticate via smb credentials using an admin account, however in Windows SMB/LSC Authenticated Scan Info consolidation we see the following 3 lines:

Access to the registry possible (SMB/registry_access) : FALSE
Extended SMB support available via openvas-smb module (Tools/Present/smb) : FALSE
Extended WMI support available via openvas-smb module (Tools/Present/wmi) : FALSE

This is regardless of whether or not we enable ‘Start Remote Registry Service’ - cloned Full and very deep, and full and very deep ultimate and changed the value to yes. If the remote registry service does not start we receive no vulnerability information. We can however manually start the service on the target machine and get results. Is there a step during install to enable the openvas-smb tool or a scan setting? Please help. Issue began after update of OpenVas/GVM. libgcrypt error was reason for new install.

Additionally, we disabled the firewall on host and greenbone machine as well as disabling selinux. which yields similar results.

**Comment by atomicturtle** [comment]
closed, 20.08 is now available
