### ISSUE TITLE
gvm-libs needs updating

### ISSUE THREAD

**Issue by atlredsox** [Atomicorp/gvm#21]
Overview: The current version of gvm-libs in the repo is now end-of-life. So gvm-libs needs to be updated to at least 10.0.1, and possibly 10.0.2.

Reason: Running scans now reports a high vulnerability for every host that states:

- **report outdated / end-of-life Scan Engine / Environment (local)**

Specifically it states that:
Installed GVM Libraries (gvm-libs) version:        10.0.0
Latest available GVM Libraries (gvm-libs) version: 10.0.1

**Comment by atomicturtle** [comment]
This is in progress right now, with the target of EL8 and FC32 for the first update

**Comment by mikch06** [comment]
Hi, sorry when i'm asking again. That means there are new rpm sources for CentOS7/8 in preparation?

**Comment by cfi-gb** [comment]
Looks this is also a duplicate of #18

**Comment by atomicturtle** [comment]
Merging this into #18
