### ISSUE TITLE
gvm.cron: Syncing SCAP before CERT feed and add missing GVM_DATA sync

### ISSUE THREAD

**Issue by cfi-gb** [Atomicorp/gvm#28]
Mainly copied from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968500 with some slight modifications:

In gvm.cron [1] the CERT feed (via greenbone-certdata-sync) is synced before the SCAP feed (via greenbone-scapdata-sync).

Currently the CERT feed sync depends on data provided by the SCAP feed and should be called after syncing the latter. This is now also documented since a few days in [2].

[1] https://github.com/Atomicorp/openvas/blob/master/src/gvm-20.8.0/gvm.cron#L6-L7
[2] https://github.com/greenbone/gvmd/pull/1237/files

**Comment by cfi-gb** [comment]
When touching the gvm.cron it could also make sense to update the syncing of the files to the "new" way (including a GVM_DATA sync) described here:

https://github.com/greenbone/gvmd/blob/v20.8.0/INSTALL.md#keeping-the-feeds-up-to-date

**Comment by atomicturtle** [comment]
Updated in release: gvm 14790
