### ISSUE TITLE
Broken on Fedora 28

### ISSUE THREAD

**Issue by kallisti5** [Atomicorp/gvm#3]
```# openvassd
openvassd: symbol lookup error: openvassd: undefined symbol: nvticache_free
```
```# rpm -qa | grep openvas
openvas-libraries-9.0.2-4714.fc28.art.x86_64
openvas-cli-1.4.5-4729.fc28.art.x86_64
openvas-scanner-5.1.1-4.fc27.x86_64
openvas-9.0.3-4743.fc28.art.noarch
openvas-manager-7.0.2-4723.fc28.art.x86_64
```

**Comment by atomicturtle** [comment]
ahh I see whats going on there, you have:

openvas-scanner-5.1.1-4.fc27.x86_64

that is a package from the fedora project (27, so your system is an upgrade?)

This is the package  you need, I'll bet you can get it with a straight dnf upgrade:
openvas-scanner-5.1.2-4731.fc28.art.x86_64
