### ISSUE TITLE
Cannot start ospsd-openvas after installing latest rpms gvm-20.8.0-14781.el8.art.noarch

### ISSUE THREAD

**Issue by max70-root** [Atomicorp/gvm#30]
Hi 
i am trying to reinstall openvas using latest rpms, but there is something wrong with python scripts.

When starting ospd-openvas i get the following error

`ospd-openvas[30688]: Traceback (most recent call last):
Sep  7 16:11:39 localhost ospd-openvas[30688]:  File "/opt/atomicorp/bin/ospd-openvas", line 6, in <module>
Sep  7 16:11:39 localhost ospd-openvas[30688]:    from pkg_resources import load_entry_point
Sep  7 16:11:39 localhost ospd-openvas[30688]:  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
Sep  7 16:11:39 localhost ospd-openvas[30688]:    @_call_aside
Sep  7 16:11:39 localhost ospd-openvas[30688]:  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
Sep  7 16:11:39 localhost ospd-openvas[30688]:    f(*args, **kwargs)
Sep  7 16:11:39 localhost ospd-openvas[30688]:  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
Sep  7 16:11:39 localhost ospd-openvas[30688]:    working_set = WorkingSet._build_master()
Sep  7 16:11:39 localhost ospd-openvas[30688]:  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
Sep  7 16:11:39 localhost ospd-openvas[30688]:    ws.require(__requires__)
Sep  7 16:11:39 localhost ospd-openvas[30688]:  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
Sep  7 16:11:39 localhost ospd-openvas[30688]:    needed = self.resolve(parse_requirements(requirements))
Sep  7 16:11:39 localhost ospd-openvas[30688]:  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
Sep  7 16:11:39 localhost ospd-openvas[30688]:    raise DistributionNotFound(req, requirers)
Sep  7 16:11:39 localhost ospd-openvas[30688]: pkg_resources.DistributionNotFound: The 'ospd-openvas==20.8.0' distribution was not found and is required by the application
Sep  7 16:11:39 localhost systemd[1]: ospd-openvas.service: Main process exited, code=exited, status=1/FAILURE
`

Don't know if it is related but directory /opt/atomicorp/lib/python3.6/site-packages is empty, all the packages are in /opt/atomicorp/lib/python3.8/site-packages, maybe wrong python version referenced in ospd-openvas.service?

**Comment by atomicturtle** [comment]
Updated in OSPd-openvas release: 14789
