### ISSUE TITLE
for centos 8, gvmd pid file is in a different location from the expected

### ISSUE THREAD

**Issue by waldo323** [Atomicorp/gvm#32]
the service appears to be running, but has the pid file in a different location.
I found this when running: systemctl status gvmd.service 
the output includes:
Sep 14 16:35:21 systemname systemd[1]: Starting GVM Manager...
Sep 14 16:35:21 systemname systemd[1]: gvmd.service: Can't open PID file /var/run/gvm/gvmd.pid (yet?) after start: No such file or directory
Sep 14 16:35:25 systemname systemd[1]: Started GVM Manager

in files:
/etc/systemd/system/multi-user.target.wants/gvmd.service:PIDFile=/var/run/gvm/gvmd.pid
/etc/systemd/system/openvas-manager.service:PIDFile=/var/run/gvm/gvmd.pid

I did find the location of the pid file: 
_$ find / -name gvmd.pid_
/run/gvm/gvmd.pid

**Comment by willemdh** [comment]
@waldo323 Same issue here => 
`systemd[1]: gvmd.service: Can't open PID file /var/run/gvm/gvmd.pid (yet?) after start: No such file or directory`

**Comment by cfi-gb** [comment]
`/var/run` is normally only a symlink to `/run` so the path should be correct (if that symlink exist).

AFAIK this message can be ignored, the pid file is just created a little bit too late then the gvmd.service file is expecting it and gvmd and the service file should still work as expected.

**Comment by atomicturtle** [comment]
closed (benign issue)
