### ISSUE TITLE
New Patch for ospd-openvas package

### ISSUE THREAD

**Issue by mikch06** [Atomicorp/gvm#33]
There is a new important patch for the ospd-openvas package https://github.com/greenbone/ospd-openvas/pull/334
It's possible to provide the rpm to atomic repo?

Thanks in advance. 
mik

**Comment by atomicturtle** [comment]
I gave it a shot but it looks like this has dependencies from the main branch, it might be better to wait until upstream has an official release. That said, we just duplicated this package repo to: https://github.com/Atomicorp/ospd-openvas if anyone wants to give it a shot

**Comment by mikch06** [comment]
Thx for your answer. Yes, i think its better to wait too. But, the service isnt' working now in the right way. 
Let's see what i can do.

**Comment by mikch06** [comment]
It's solved now for me.
I patched the ospd-openvas egg package myself. Now it runs with the newest bugfixes.

**Comment by atomicturtle** [comment]
You wanna do a pull request of your fixes to https://github.com/Atomicorp/ospd-openvas ? Id be happy to include them

**Comment by atomicturtle** [comment]
Implemented in atomic-testing with the 21.04 update (fc33 and fc34)
