### ISSUE TITLE
Support for RADIUS is not available

### ISSUE THREAD

**Issue by YilunHunag** [Atomicorp/gvm#36]
As title, 
I installed gvm using yum, and found that doesn't support for RADIUS.
Is that anything wrong? or it doesn't  build  including RADIUS?

**Comment by atomicturtle** [comment]
We'd need a hand on figuring that out, I dont have that here to work with and I dont see what would need to be done

**Comment by cfi-gb** [comment]
AFAIK similar to the LDAP support gvm-libs needs to be build against freeradius-client / radcli for RADIUS support:

https://github.com/bjoernricks/gvm-libs/blob/b0e1f5ef9916062a2b48b84004dc2922c2ef5a08/util/CMakeLists.txt#L97-L116

**Comment by atomicturtle** [comment]
Added in 22.04
