### ISSUE TITLE
Systemd Timer instead of Cron

### ISSUE THREAD

**Issue by securitytime** [Atomicorp/gvm#37]
Hello,

I noticed that feed updates are handled via the cron job /etc/cron.daily/gvm

Would it be feasible to switch from cron to systemd timers?

I find systemd timers much easier to manage. Nowadays, most services don't use cron anymore.

**Comment by atomicturtle** [comment]
By all means, send a pull request

**Comment by atomicturtle** [comment]
Closing this one out, I like the idea but we need the flexibility of the script approach for containers.  This would be a really good contrib/ type project if you'd like to send a PR
