### ISSUE TITLE
Cannot change admin password

### ISSUE THREAD

**Issue by securitytime** [Atomicorp/gvm#38]
Hello,

So I installed GVM. The last thing I did was running `gvm-setup` during which I set the admin password.

Now I wanted to change the admin password via the console. I ran as root `gvmd --user=admin --new-password=NEWPASSWORD`.

However, the password did not change.  Looking at `/var/log/gvm/gvmd.log` I see the following error message:

```
md   main:MESSAGE:2020-10-26 10h20.40 utc:30042:    Greenbone Vulnerability Manager version 20.08.0 (DB revision 233)
md manage:   INFO:2020-10-26 10h20.40 utc:30042:    Modifying user password.
md manage:WARNING:2020-10-26 10h20.40 utc:30042: sql_open: PQconnectPoll failed
md manage:WARNING:2020-10-26 10h20.40 utc:30042: sql_open: PQerrorMessage (conn): FATAL:  role "root" does not exist
md manage:WARNING:2020-10-26 10h20.40 utc:30042: init_manage_process: sql_open failed
```

**Comment by atomicturtle** [comment]
You probably can only do that from the gvm user context, postgres is weird like that

**Comment by securitytime** [comment]
You are correct! When I run the command as the "gvm" user then it works.
