### ISSUE TITLE
Not a Bug

### ISSUE THREAD

**Issue by delatbabel** [Atomicorp/gvm#40]
Just leaving a note -- not a bug, not an issue.

I have spent a lot of time over the last few months attempting to get OpenVAS / GVM installed on various Linux distributions. Ubuntu, CentOS, Fedora, Kali Linux, etc.  All of which have proven to be unstable -- either the system doesn't compile, doesn't install, doesn't run, or runs after a fashion for a while but then fails to keep running after various updates (e.g. switching the vulnerability feed to a new URL some time after the OpenVAS v9 release).  In most of these cases the GVM support channels have been less than helpful.

I even abandoned GVM at one point and started looking at alternative packages but I couldn't find anything that actually did what I wanted it to do -- internal and external penetration testing on a range of hosts.

This is the first set of packages and installation instructions that I have encountered that actually install and run reliably and enable me to load up the vulnerability database and get GVM running, with all of its dependencies.

Well done and thank you.

**Comment by atomicturtle** [comment]
Wow thank you so much for this! Happy that you've got everything working, and I hope this continues to help you out!
