### ISSUE TITLE
Empyt result on GVM - CentOS 8

### ISSUE THREAD

**Issue by Spleeff** [Atomicorp/gvm#41]
Hello,
I have a fresh install of GVM/OpenVAS on CentOS 8.
The installation went smoothly following your guide but when I run a scan it only takes a few seconds and I get an empty result and a severity "N/A".
I just checked the logs but I don't see anything to justify this behavior.

Could you help me on this ?

Many thanks

**Comment by KPS-MWT** [comment]
If the taget is not pingable, it is considered "dead" as default.
You can change that by altering the scan configuration (clone if preset) to not marking non-pingable Host:

configuration > Scan Configuration > Edit > Port Scanner Family > Ping Host > Edit > "Mark unrechable Hosts as dead (not scanning)" > set to "No"

**Comment by atomicturtle** [comment]
closed/no response
