### ISSUE TITLE
CentOS Stream

### ISSUE THREAD

**Issue by RBloemers** [Atomicorp/gvm#44]
Since the future of Centos 8 is limited now, any updates on when CentOS stream will be supported?

At the moment it wants to uninstall GVM when doing a CentOS 8 to CentOS stream upgrade.

**Comment by KPS-MWT** [comment]
Did a new install on CentOS Stream yesterday, works like a charm. It may be a single dependency.

@RBloemers: Did it tell which package(s) triggered the uninstall?

**Comment by atomicturtle** [comment]
yeah my gut feeling is that stream wont be a problem, since we're also building this on fedora (and will continue to). That said, we absolutely plan on supporting Rocky linux 8 for this

**Comment by atomicturtle** [comment]
And rocky 8 support is now complete!
