### ISSUE TITLE
Centos7, gvmd, OpenVAS Scanner

### ISSUE THREAD

**Issue by C1ph3R-s** [Atomicorp/gvm#47]
Hi,

Do you have any solutions problems below?

OS : CentOS7
GVM: GVM9.0

My gsad and OpenVAS Scanner services down.

```
● gvmd.service - OpenVAS Manager
   Loaded: loaded (/usr/lib/systemd/system/gvmd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sun 2021-01-24 14:22:40 CET; 19h ago
  Process: 11629 ExecStart=/usr/sbin/gvmd -f $OPTIONS (code=exited, status=1/FAILURE)

Jan 24 14:22:38 localhost.localdomain systemd[1]: gvmd.service: control process exited, code=exited status=1
Jan 24 14:22:38 localhost.localdomain systemd[1]: Failed to start OpenVAS Manager.
Jan 24 14:22:38 localhost.localdomain systemd[1]: Unit gvmd.service entered failed state.
Jan 24 14:22:38 localhost.localdomain systemd[1]: gvmd.service failed.
Jan 24 14:22:40 localhost.localdomain systemd[1]: gvmd.service holdoff time over, scheduling restart.
Jan 24 14:22:40 localhost.localdomain systemd[1]: Stopped OpenVAS Manager.
Jan 24 14:22:40 localhost.localdomain systemd[1]: start request repeated too quickly for gvmd.service
Jan 24 14:22:40 localhost.localdomain systemd[1]: Failed to start OpenVAS Manager.
Jan 24 14:22:40 localhost.localdomain systemd[1]: Unit gvmd.service entered failed state.
Jan 24 14:22:40 localhost.localdomain systemd[1]: gvmd.service failed.
```

```
● openvas-scanner.service - OpenVAS Scanner
   Loaded: loaded (/usr/lib/systemd/system/openvas-scanner.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sun 2021-01-24 14:22:40 CET; 19h ago
  Process: 11627 ExecStart=/usr/sbin/openvassd $SCANNER_SOCKET $SCANNER_MODE $SCANNER_GROUP $SCANNER_OWNER (code=exited, status=203/EXEC)

Jan 24 14:22:38 localhost.localdomain systemd[1]: openvas-scanner.service: control process exited, code=exited status=203
Jan 24 14:22:38 localhost.localdomain systemd[1]: Failed to start OpenVAS Scanner.
Jan 24 14:22:38 localhost.localdomain systemd[1]: Unit openvas-scanner.service entered failed state.
Jan 24 14:22:38 localhost.localdomain systemd[1]: openvas-scanner.service failed.
Jan 24 14:22:40 localhost.localdomain systemd[1]: openvas-scanner.service holdoff time over, scheduling restart.
Jan 24 14:22:40 localhost.localdomain systemd[1]: Stopped OpenVAS Scanner.
Jan 24 14:22:40 localhost.localdomain systemd[1]: start request repeated too quickly for openvas-scanner.service
Jan 24 14:22:40 localhost.localdomain systemd[1]: Failed to start OpenVAS Scanner.
Jan 24 14:22:40 localhost.localdomain systemd[1]: Unit openvas-scanner.service entered failed state.
Jan 24 14:22:40 localhost.localdomain systemd[1]: openvas-scanner.service failed.
```

Moreover my gsad.log contains these logs:

```
md manage:WARNING:2021-01-24 13h21.45 utc:11522: sql_exec_internal: SQL: CREATE OR REPLACE FUNCTION hosts_contains (text, text) RETURNS boolean AS '/usr/lib64/libgvm-pg-server', 'sql_hosts_contains' LANGUAGE C IMMUTABLE;
md manage:WARNING:2021-01-24 13h21.45 utc:11522: sqlv: sql_exec_internal failed
md   main:MESSAGE:2021-01-24 13h21.46 utc:11526:    Greenbone Vulnerability Manager version 9.0.0 (DB revision 221)
md manage:WARNING:2021-01-24 13h21.46 utc:11526: sql_exec_internal: PQexec failed: ERROR:  could not load library "/usr/lib64/libgvm-pg-server.so": /opt/atomicorp/atomic/root/usr/lib64/libgpgme.so.11: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference
```

and when I want to login on the GUI as admin, it present the "GVM service down" string.

Do you have any solution for that problem?

**Comment by atomicturtle** [comment]
There wont be any more updates for that version since its now EOL.  The 20.08 update is available on EL8 and Fedora now, so you could switch to that and get a working build today. EL7 is currently blocked by: https://github.com/Atomicorp/gvm-libs/issues/1

**Comment by atomicturtle** [comment]
Going to close this one out since we've got GVM on EL8 (rocky/redhat) and Fedora. If the interest is there we could revisit EL7 support in the future

**Comment by dekumar4** [comment]
Trying to install openvas-scanner and getting following error on Oracle Linux 7.9. Could you please suggest the solution for it ? 

error: %pre(openvas-scanner-7.0.0-9465.el7.art.x86_64) scriptlet failed, exit status 2
Error in PREIN scriptlet in rpm package openvas-scanner-7.0.0-9465.el7.art.x86_64
  Installing : greenbone-vulnerability-manager-11.0.0-9461.el7.art.noarch                                                 2/2
error: openvas-scanner-7.0.0-9465.el7.art.x86_64: install failed
  Verifying  : greenbone-vulnerability-manager-11.0.0-9461.el7.art.noarch                                                 1/2
  Verifying  : openvas-scanner-7.0.0-9465.el7.art.x86_64                                                                  2/2

Installed:
  greenbone-vulnerability-manager.noarch 0:11.0.0-9461.el7.art

Failed:
  openvas-scanner.x86_64 0:7.0.0-9465.el7.art

Complete!


NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9
