### ISSUE TITLE
conflicting package error when performing a yum upgrade

### ISSUE THREAD

**Issue by eclay11** [Atomicorp/gvm#5]
Hello,  We have openvas installed on a system running COS 7.5.1804 it has both the epel and atomic repos configured.  When I perform a 'yum upgrade' I get a complaint about conflicting packages related or that are dependency of openvas.

`Transaction check error:
  file /usr/lib/python2.7/site-packages/socks.py conflicts between attempted installs of python2-pysocks-1.6.8-5.el7.noarch and python-SocksiPy-1.00-4.el7.art.noarch
  file /usr/lib/python2.7/site-packages/socks.pyc conflicts between attempted installs of python2-pysocks-1.6.8-5.el7.noarch and python-SocksiPy-1.00-4.el7.art.noarch
  file /usr/lib/python2.7/site-packages/socks.pyo conflicts between attempted installs of python2-pysocks-1.6.8-5.el7.noarch and python-SocksiPy-1.00-4.el7.art.noarch
`

It looks like our system is trying to upgrade python2-pysocks and python34-idna from the epel repo which has a dependency of python-SocksiPy from the atomic repo.  I currently only see the following two packages isntalled on this server.
`# rpm -qa|grep -iE 'python2-pysocks|python34-idna|python-socksipy'
python34-idna-2.1-1.el7.noarch
python2-pysocks-1.6.7-1.el7.noarch
`

I should mention that we also have nessus installed on this server but the conflicts seem to be related to openvas 9.

**Comment by Martha-GitHub** [comment]
same issue with our system, no idea

**Comment by atomicturtle** [comment]
I can reproduce this here, update is forthcoming!

**Comment by Martha-GitHub** [comment]
thanks for your comment

**Comment by JasonEde** [comment]
I've been unable to update for a while because of this. I tried uninstalling openvas to update and reinstall it, but it broke the database. I've restored virtual back to pre-upgrade state and will await the resolution

**Comment by jsnod** [comment]
Just hit this as well, unable to update from CentOS 7.5 => 7.6 due to this.

**Comment by seanr0** [comment]
Hopping in here - same issue. 

edit: just an fyi, if you direly need to upgrade out of whatever CentOS version you're on to 7.6, you can just do this, and the update goes through:

`yum -y update --exclude=*socks*`

Tried this on a test clone of my production OpenVAS box, and it's now on 7.6. I tested some scans and it doesn't appear to break anything. I'd still prefer to wait for something official, but this works if you need a quick and dirty "right now" fix.

**Comment by atomicturtle** [comment]
This dependency has been retired from the repo, thanks for the report!
