### ISSUE TITLE
21.04 Update

### ISSUE THREAD

**Issue by rsaeks** [Atomicorp/gvm#51]
Just wanted to put a post in here for updating the atomic repo to the 21.04 release:

https://community.greenbone.net/t/gvm-21-04-stable-initial-release-2021-04-16/8942/3

**Comment by KAlamurov** [comment]
+1

**Comment by hdkiller** [comment]
I am also looking for the update.

**Comment by jfdarveau** [comment]
Hi wouldn't hold my breath. I was told that they were working in the 20.8.1 update 2 months ago and no commit has been made for over 4 months. :(

**Comment by atomicturtle** [comment]
@jfdarveau Which just goes to show you're not following atomic-testing. 

FC33 and FC34 packages have been in progress in that repo for some time

**Comment by mikch06** [comment]
Is atomic-testing a repo on atomic or github? 
Can't find.

Thx!

**Comment by mikch06** [comment]
rpm's are in the repos and update works fine.
See other issues for migrating the database.
