### ISSUE TITLE
GVM update to version 21.04 - HowTo

### ISSUE THREAD

**Issue by Spleeff** [Atomicorp/gvm#52]
Hello,

By executing a yum update, I get the new version of GVM unfortunately it is not possible for me to log into the web interface after the update with the following message:
"The Greenbone Vulnerability Manager service is not responding. This could be due to system maintenance. Please try again later, check the system status, or contact your system administrator".

Could you tell me how to update on a RHEL 8 system ?

Thanks for your help

**Comment by Doudoux2** [comment]
Hello

I have the same problem.

More information

```bash
gvmd -m

(gvmd:2064): md manage-WARNING **: 20:21:47.549: sql_open: PQconnectPoll failed
(gvmd:2064): md manage-WARNING **: 20:21:47.550: sql_open: PQerrorMessage (conn): FATAL:  role "root" does not exist
(gvmd:2064): md manage-WARNING **: 20:21:47.550: init_manage_open_db: sql_open failed
```

```bash
postgres --version

postgres (PostgreSQL) 10.15
```



Thanks

**Comment by Doudoux2** [comment]
I have resoled my problem.

Try:

```bash
# with root privileges
# stop service
/bin/systemctl stop gvmd.service
/bin/systemctl stop gsad.service
/bin/systemctl stop ospd-openvas.service

# switch to gvm user
su gvm

# migrate
gvmd -m

# wait...... and wait.....


# return previous login
exit

# restart service
/bin/systemctl start gvmd.service
/bin/systemctl start gsad.service
/bin/systemctl start ospd-openvas.service

````

**Comment by Shaguu** [comment]
Hello,

You do these commands after updating GVM via yum update, correct ?

Thanks

**Comment by Doudoux2** [comment]
Hello

> You do these commands after updating GVM via yum update, correct ?
yes

I think I was not patient enough. And maybe reboot/stop openvas before database update ending.
Hence my problem.

**Comment by mikch06** [comment]
While database migration is running you can tail -f the gvmd.log -> to see the progress

**Comment by mikch06** [comment]
> 
> 
> I have resoled my problem.
> 
> Try:
> 
> ```shell
> # with root privileges
> # stop service
> /bin/systemctl stop gvmd.service
> /bin/systemctl stop gsad.service
> /bin/systemctl stop ospd-openvas.service
> 
> # switch to gvm user
> su gvm
> 
> # migrate
> gvmd -m
> 
> # wait...... and wait.....
> 
> 
> # return previous login
> exit
> 
> # restart service
> /bin/systemctl start gvmd.service
> /bin/systemctl start gsad.service
> /bin/systemctl start ospd-openvas.service
> ```

This was the solution for me. Thanks a lot!

**Comment by Spleeff** [comment]
I confirm, it works for me too, thanks for your help !

**Comment by atomicturtle** [comment]
I'm still looking for a good way to detect an upgrade state. Its doable from the RPM side, but this process is too interactive to do it in there, so it'd have to be handled in gvm-setup. This is actually how it was handled in older versions of that, but greenbone made some huge advancements here (which are terrific, especially on large datasets. Well done @cfi-gb & greenbone!) so the old way of detecting it isnt an option. 

The hacky thing would be to ask in gvm-setup if this is an upgrade, in a pinch thats doable. Id rather it was self detecting though

**Comment by atomicturtle** [comment]
Closing this as out of date, since we're now on 21.4.2. I havent seen any issues with 21.4.0->21.4.2 updates
