### ISSUE TITLE
Update repository atomic corp with last version of gvm-libraries

### ISSUE THREAD

**Issue by antoweb** [Atomicorp/gvm#55]
From some days my scan result go to Severity != due the gvm-libraries version outdated.
Please update the rpm packages on the repository.
Thanks

**Comment by nlarenti** [comment]
> From some days my scan result go to Severity != due the gvm-libraries version outdated. Please update the rpm packages on the repository. Thanks

Quoted

**Comment by Shaguu** [comment]
Any updates about this ?

**Comment by aalex954** [comment]
An update to verion 21.4.3 would be much appreciated!

**Comment by rsaeks** [comment]
Would love to see this as well!

**Comment by fendiroccia** [comment]
Please update! ;-) Thank you.

**Comment by atomicturtle** [comment]
packages are in the atomic-testing channel now

**Comment by fendiroccia** [comment]
Could you please tell me how to download them?
Thank you!

**Comment by rsaeks** [comment]
Is there any information about where this atomic-testing channel resides? I didn't see a branch for this and checking the various project readme.md files don't have any information either. (I'm sure it's an easy one, but just not finding any reference to this to get me in the right direction)

**Comment by fendiroccia** [comment]
Hi atomicturtle,
could the Testing Channel be the follower?
[https://updates.atomicorp.com/channels/atomic-testing/centos/8/x86_64/RPMS/gvm-libs-21.4.3-23769.el8.art.x86_64.rpm]
In this case I have two questions, the first is which package I have to use for Rocky Linux, the second is how do I install the package? Do I simply download and install the RPM or are there any other way?
Thanks!

**Comment by atomicturtle** [comment]
Sure, you can enable the testing channel from the command line:

yum --enablerepo=atomic-testing upgrade

that said, I just published the packages to the main repo, so you won't need to grab them from testing any more.
