### ISSUE TITLE
Reconfigure the default OSPD scanner socket path

### ISSUE THREAD

**Issue by presianbg** [Atomicorp/gvm#56]
Hi,

I hit the following issue:
https://community.greenbone.net/t/gvmd-could-not-connect-to-scanner/11109

TL;DR - the installer uses `/var/run/ospd/ospd-openvas.sock` , but the manager is not configured for this custom path.
Fix - https://github.com/greenbone/gvmd/blob/v21.4.4/INSTALL.md#configure-the-default-ospd-scanner-socket-path

Cheers,
PY

**Comment by atomicturtle** [comment]
Nod, the manager does look for the socket at /var/run/ospd/ospd-openvas.sock, its part of the systemd file:

ExecStart=/usr/sbin/gvmd --osp-vt-update=/var/run/ospd/ospd-openvas.sock $OPTIONS
