### ISSUE TITLE
dnf update on rocky linux to 21.4.4 broke things

### ISSUE THREAD

**Issue by ghost** [Atomicorp/gvm#57]
ospd-openvas is trying to write to /var/run/gvm which has changed to /var/run/gvmd and gvmd can't find the ospd-openvas socket - had to add its path in /etc/sysconfig/gvmd

**Comment by ghost** [comment]
actually had to add OPTIONS="--scanner-host=/var/run/ospd/ospd-openvas.sock"

**Comment by l4rsV** [comment]
had similar issues but did different things:
 mkdir /var/run/gvm
 chown gvm:gvm /var/run/gvm
 
 ln -s  /var/run/ospd/ospd-openvas.sock /var/run/ospd/ospd.sock
 chown -h gvm:gvm /var/run/ospd/ospd.sock
 
 Lets see if this works

**Comment by atomicturtle** [comment]
@l4rsV My guess here is its not surviving a reboot (there are some special configs w/ systemd to handle this) , could you confirm that for me? This project is quite the moving target huh

**Comment by MiroVerleysen** [comment]
@sclark46 I tried to add 
`OPTIONS="--scanner-host=/var/run/ospd/ospd-openvas.sock"`
to /etc/sysconfig/gvmd but even after a full reboot I keep getting the following error in gvmd.log when trying to do a scan: `Could not connect to Scanner at /run/ospd/ospd-openvas.sock`. 

After a reboot the added line is still there. And the socket file is in that dir: 
![image](https://user-images.githubusercontent.com/55786561/164197994-d01641b4-e021-49f8-add6-614fb4e429c6.png)

In the gvmd.log file I keep getting this error: `osp_scanner_feed_version: failed to get scanner_feed_version. OSPd OpenVAS is still starting`

And in the ospd-scanner.log file I get this error: `ERROR: (ospd_openvas.lock) Could not create parent dir /var/run/gvm for lock file. [Errno 13] Permission denied: '/var/run/gvm'`

**Comment by ghost** [comment]
lookl like restart removes the ln of /run/gvmd /run/gvm - recreated link restarted everything - mine seems to be working again.

**Comment by MiroVerleysen** [comment]
Mine is working again too. Thanks!

**Comment by ghost** [comment]
good - but I wish the devs would create a proper fix.

**Comment by atomicturtle** [comment]
I added a workaround to OSPd-openvas-21.4.4-26250 to create one by way of a systemd tmpfile.

**Comment by b-keller** [comment]
Hi, 

OSPd-openvas-21.4.4-26250 was not proposed for RockyLinux 8.x ?

Thx

**Comment by andreborsatti** [comment]
Hi,

I have the same problem, is there any solution?

tail -f /var/log/gvmd.log

md manage:WARNING:2022-07-26 14h23.23 UTC:32863: osp_scanner_feed_version: failed to connect to /var/run/ospd/ospd.sock

my NVT Feed in No NVT's Available.

![image](https://user-images.githubusercontent.com/110043687/181030665-2a5d3af2-0ac3-4b72-b78b-aed31b01917d.png)

Anyone else with the same problem?

thanks for helping!
