### ISSUE TITLE
Openvas-scanner version: 22.4.1

### ISSUE THREAD

**Issue by R136a1-exe** [Atomicorp/gvm#65]
Hello,

An update is planned to switch to the latest version of openvas-scanner: 22.4.1 ?

The scans reports a high vulnerability for every host that states:

    report outdated / end-of-life Scan Engine / Environment (local)

Thx for all your job !

**Comment by atomicturtle** [comment]
I published the 22.4.1 packages back in January for EL8/9 and FC36+. Are you on an older distro maybe?

**Comment by R136a1-exe** [comment]
For Rocky linux too ? If yes, i dont understand my mistake 

```
# uname -a
Linux xxxx 4.18.0-425.13.1.el8_7.x86_64 #1 SMP Tue Feb 21 19:25:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/rocky-release
Rocky Linux release 8.7 (Green Obsidian)
# cat /etc/yum.repos.d/atomic.repo
# Name: Atomic Rocket Turtle RPM Repository for Rocky / CentOS / Red Hat Enterprise Linux 8 -
# URL: http://www.atomicrocketturtle.com/
[atomic]
name = Rocky / CentOS / Red Hat Enterprise Linux $releasever - atomic
mirrorlist = https://updates.atomicorp.com/channels/mirrorlist/atomic/centos-$releasever-$basearch
enabled = 0
protect = 0
gpgkey = https://www.atomicorp.com/RPM-GPG-KEY.atomicorp.txt
gpgcheck = 1

# Almost Stable, release candidates for [atomic]
[atomic-testing]
name = Rocky / CentOS / Red Hat Enterprise Linux $releasever - atomic - (Testing)
mirrorlist = https://updates.atomicorp.com/channels/mirrorlist/atomic-testing/centos-$releasever-$basearch
enabled = 1
protect = 0
gpgkey = https://www.atomicorp.com/RPM-GPG-KEY.atomicorp.txt
gpgcheck = 1

```

**Comment by R136a1-exe** [comment]
So its ok, i do "dnf module disable atomicorp" and i enable stable repo + testing repo and its almost ok. Some corrections to do.

I have a strange warning in /var/log/gvm/ospd-scanner.log

` tail -f /var/log/gvm/ospd-scanner.log
OSPD[3079] 2023-03-21 14:08:14,207: WARNING: (ospd_openvas.messaging.mqtt) Could not connect to MQTT broker, error was: [Errno 99] Cannot assign requested address. Trying again in 10s.
OSPD[3079] 2023-03-21 14:08:24,216: WARNING: (ospd_openvas.messaging.mqtt) Could not connect to MQTT broker, error was: [Errno 99] Cannot assign requested address. Trying again in 10s.
OSPD[3079] 2023-03-21 14:08:34,227: WARNING: (ospd_openvas.messaging.mqtt) Could not connect to MQTT broker, error was: [Errno 99] Cannot assign requested address. Trying again in 10s.
OSPD[3079] 2023-03-21 14:08:44,237: WARNING: (ospd_openvas.messaging.mqtt) Could not connect to MQTT broker, error was: [Errno 99] Cannot assign requested address. Trying again in 10s.
OSPD[3079] 2023-03-21 14:08:54,247: WARNING: (ospd_openvas.messaging.mqtt) Could not connect to MQTT broker, error was: [Errno 99] Cannot assign requested address. Trying again in 10s.
OSPD[3079] 2023-03-21 14:09:04,258: WARNING: (ospd_openvas.messaging.mqtt) Could not connect to MQTT broker, error was: [Errno 99] Cannot assign requested address. Trying again in 10s.
OSPD[3079] 2023-03-21 14:09:14,266: WARNING: (ospd_openvas.messaging.mqtt) Could not connect to MQTT broker, error was: [Errno 99] Cannot assign requested address. Trying again in 10s.
OSPD[3079] 2023-03-21 14:09:24,276: WARNING: (ospd_openvas.messaging.mqtt) Could not connect to MQTT broker, error was: [Errno 99] Cannot assign requested address. Trying again in 10s.
OSPD[3079] 2023-03-21 14:09:34,287: WARNING: (ospd_openvas.messaging.mqtt) Could not connect to MQTT broker, error was: [Errno 99] Cannot assign requested address. Trying again in 10s.
OSPD[3079] 2023-03-21 14:09:44,296: WARNING: (ospd_openvas.messaging.mqtt) Could not connect to MQTT broker, error was: [Errno 99] Cannot assign requested address. Trying again in 10s.
`

**Comment by R136a1-exe** [comment]
Last comment :)

openvas-setup and check if notus-scanner and mosquitto are enable and running.
