### ISSUE TITLE
No candidates for gvm - CentOS 8 Stream

### ISSUE THREAD

**Issue by christianbj87** [Atomicorp/gvm#66]
Hi, i followed all the steps from the guide and i got the message:
There is no candidate for gvm on Centos 8.

[root@localhost ~]# yum install gvm
Última comprobación de caducidad de metadatos hecha hace 0:00:05, el mar 21 mar 2023 18:11:37 -03.
No hay coincidencias para el argumento: gvm
Error: No se pudo encontrar ningún resultado: gvm

History:
   26  wget   https://updates.atomicorp.com/installers/atomic --no-check-certificate |  sh
   27  yum config-manager --set-enabled powertools
   28  yum install epel-release
   29  yum install gvm
   30  ls
   31  ls atomic
   32  cd atomic
   33  cat atomic
   34  ls -la
   35  chmod +x atomic
   36  ./atomic 
   37  yum config-manager --set-enabled powertools
   38  yum install epel-release
   39  yum install gvm

[root@localhost ~]# uname -a
Linux localhost.localdomain 4.18.0-448.el8.x86_64 #1 SMP Wed Jan 18 15:02:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Any ideas?

Thanks!!

**Comment by atomicturtle** [comment]
That looks like the file is empty, either way it was built for Rocky 8 or RHEL8, I'm not sure stream will work with the installer. You could also use Fedora which is what I usually build it for first.

**Comment by christianbj87** [comment]
Hi! i folled again the steps and now it is installed. Thanks.
