### ISSUE TITLE
Macro %undefine

### ISSUE THREAD

**Issue by becchett** [Atomicorp/gvm#71]
Dear friends,
I've got a virtual machine Almalinux 9.2 and atomic-release-1.0-23.el9.art.noarch,
but when I search something always appears this error:
`
[root@openvas yum.repos.d]# dnf search greenbone --disablerepo=atomic
error: /etc/rpm/macros.atomic-config: line 3: Macro %undefine is a built-in (%define)
error: /etc/rpm/macros.atomic-config: line 5: Macro %undefine is a built-in (%define)
error: /etc/rpm/macros.atomic-config: line 3: Macro %undefine is a built-in (%define)
error: /etc/rpm/macros.atomic-config: line 5: Macro %undefine is a built-in (%define)
Last metadata expiration check: 0:32:38 ago on Thu Nov  9 17:28:42 2023.
..`

As you now the content of macros file is

`[root@openvas yum.repos.d]# more /etc/rpm/macros.atomic-config
%scl atomic

%undefine nfsmountable

%undefine rh_layout`

Any ideas ? 
Thanks a lot
Best Regards
Enrico

**Comment by becchett** [comment]
resolved

**Comment by WerVa** [comment]
@becchett  how you resolved this?
