### ISSUE TITLE
Dependency errors (cont'd from #5)

### ISSUE THREAD

**Issue by seanr0** [Atomicorp/gvm#8]
`Error: Package: wapiti-2.3.0-5.el7.art.noarch (@atomic)
           Requires: python-SocksiPy
           Removing: python2-pysocks-1.6.7-1.el7.noarch (@epel)
               python-SocksiPy
           Updated By: python2-pysocks-1.6.8-6.el7.noarch (epel)
               Not found
`

I'm now receiving this error when trying to run a yum update && yum upgrade on our CentOS7 openvas box. Could it be possibly related to [this](https://github.com/Atomicorp/openvas/issues/5) same issue that was closed this morning? I saw that the dependency was removed from the repo as the solution. Any ideas? Or is this unrelated to the repo?

**Comment by atomicturtle** [comment]
Well it looks like its saying the EPEL package python2-pysocks-1.6.8-6 isnt found there. So not directly related, maybe your cache is out of date?

**Comment by seanr0** [comment]
I think I've gotten it figured out. Had to reinstall a package instead of just updating it. The dependency issue just threw me off as it was the same package. Sorry!
