### ISSUE TITLE
openvas (greenbone-vulnerability-manager) will not install. conflicting packages.

### ISSUE THREAD

**Issue by jacobamey** [Atomicorp/gvm#9]
Hi all, I am attempting to install to CentOS 7 (7.5.1804)

after adding the repo to my host using:
`wget -q -O - https://updates.atomicorp.com/installers/atomic | sh`

I try to install openvas:
`yum install openvas`

I receive a message that this has been replaced by Package **greenbone-vulnerability-manager** 
 
`openvas is obsoleted by greenbone-vulnerability-manager, trying to install greenbone-vulnerability-manager-10.0.0-6871.el7.art.noarch instead`

So yum switches to greenbone instead, builds its list of dependencies, I answer yes for install but receive a transaction error.

```
Transaction check error:
  file /usr/bin/openvas-nasl conflicts between attempted installs of openvas-scanner-6.0.0-6872.el7.art.x86_64 and openvas-libraries-9.0.3-6672.el7.art.x86_64
  file /usr/bin/openvas-nasl-lint conflicts between attempted installs of openvas-scanner-6.0.0-6872.el7.art.x86_64 and openvas-libraries-9.0.3-6672.el7.art.x86_64
  file /usr/lib64/libopenvas_misc.so conflicts between attempted installs of openvas-scanner-6.0.0-6872.el7.art.x86_64 and openvas-libraries-9.0.3-6672.el7.art.x86_64
  file /usr/lib64/libopenvas_nasl.so conflicts between attempted installs of openvas-scanner-6.0.0-6872.el7.art.x86_64 and openvas-libraries-9.0.3-6672.el7.art.x86_64
  file /usr/share/man/man1/openvas-nasl.1.gz conflicts between attempted installs of openvas-scanner-6.0.0-6872.el7.art.x86_64 and openvas-libraries-9.0.3-6672.el7.art.x86_64
```
I am halted here as the install does not happen. Assistence would be much appreciated. I also noticed green bone says version 10 which I thought was beta? Is it possible to just request version 9?

Edit:
When performing a yum with a show duplicates option:
`yum --showduplicates list greenbone-vulnerability-manager`

gives two versions but all are version 10:
[greenbone-vulnerability-manager.noarch                                                                10.0.0-6865.el7.art                                                                atomic
greenbone-vulnerability-manager.noarch                                                                10.0.0-6871.el7.art                                                                atomic](url)

Edit 2:
The oldest available OpenVAS package is:
**OpenVAS version 9.0.0-2795**

We are seeing the same conflicts when trying to install that instead as it will automatically jump to install the greenbone-vulnerability-manager since OpenVAS is "obsolete".

**Comment by bmel343** [comment]
I have the same issue. CentOS Core 7.6.1810
>Transaction check error:
>  file /usr/bin/openvas-nasl from install of openvas-scanner-6.0.0-6872.el7.art.x86_64 conflicts with file from package openvas-libraries-9.0.3-6672.el7.art.x86_64
>  file /usr/bin/openvas-nasl-lint from install of openvas-scanner-6.0.0-6872.el7.art.x86_64 conflicts with file from package openvas-libraries-9.0.3-6672.el7.art.x86_64
>  file /usr/lib64/libopenvas_misc.so from install of openvas-scanner-6.0.0-6872.el7.art.x86_64 conflicts with file from package openvas-libraries-9.0.3-6672.el7.art.x86_64
>  file /usr/lib64/libopenvas_nasl.so from install of openvas-scanner-6.0.0-6872.el7.art.x86_64 conflicts with file from package openvas-libraries-9.0.3-6672.el7.art.x86_64
>  file /usr/share/man/man1/openvas-nasl.1.gz from install of openvas-scanner-6.0.0-6872.el7.art.x86_64 conflicts with file from package openvas-libraries-9.0.3-6672.el7.art.x86_64

**Comment by atomicturtle** [comment]
is this an environment with a previous install of openvas, or is this a new install?

**Comment by jacobamey** [comment]
So for me a bit of both. I was attempting to install and had it all up and running with the exception of some libgcrypt and libgpg-error errors. I believe issue #7  is talking about that one. 

I yum removed, rpm -e what was left then performed a updatedb with a locate to find any residual files and manually removed those.

So I had a clean start. But OpenVAS was there before. Version 9.0.3 I believe. At this time I see no packages referencing greenbone or openvas. I may have some residual libraries though but unsure.

**Comment by bmel343** [comment]
Mine was a fresh install

**Comment by bchase78** [comment]
I have the same Problem.  
fresh install
CentOS Linux release 7.6.1810 (Core)

> Transaction check error:
>   file /usr/bin/openvas-nasl from install of openvas-scanner-6.0.0-6872.el7.art.x86_64 conflicts with file from package openvas-libraries-9.0.3-6672.el7.art.x86_64
>   file /usr/bin/openvas-nasl-lint from install of openvas-scanner-6.0.0-6872.el7.art.x86_64 conflicts with file from package openvas-libraries-9.0.3-6672.el7.art.x86_64
>   file /usr/lib64/libopenvas_misc.so from install of openvas-scanner-6.0.0-6872.el7.art.x86_64 conflicts with file from package openvas-libraries-9.0.3-6672.el7.art.x86_64
>   file /usr/lib64/libopenvas_nasl.so from install of openvas-scanner-6.0.0-6872.el7.art.x86_64 conflicts with file from package openvas-libraries-9.0.3-6672.el7.art.x86_64
>   file /usr/share/man/man1/openvas-nasl.1.gz from install of openvas-scanner-6.0.0-6872.el7.art.x86_64 conflicts with file from package openvas-libraries-9.0.3-6672.el7.art.x86_64
> 
> Error Summary

**Comment by wlgrayjr** [comment]
I am having the same issue. 
RHEL 7.5
Transaction check error:
file /usr/bin/openvas-nasl from install of openvas-libraries-9.0.3-6672.el7.art.x86_64 conflicts with file from package openvas-scanner-6.0.0-6872.el7.art.x86_64
file /usr/bin/openvas-nasl-lint from install of openvas-libraries-9.0.3-6672.el7.art.x86_64 conflicts with file from package openvas-scanner-6.0.0-6872.el7.art.x86_64
file /usr/lib64/libopenvas_misc.so from install of openvas-libraries-9.0.3-6672.el7.art.x86_64 conflicts with file from package openvas-scanner-6.0.0-6872.el7.art.x86_64
file /usr/lib64/libopenvas_nasl.so from install of openvas-libraries-9.0.3-6672.el7.art.x86_64 conflicts with file from package openvas-scanner-6.0.0-6872.el7.art.x86_64
file /usr/share/man/man1/openvas-nasl.1.gz from install of openvas-libraries-9.0.3-6672.el7.art.x86_64 conflicts with file from package openvas-scanner-6.0.0-6872.el7.art.x86_64

**Comment by pawprint** [comment]
Same problem here CentOS 7 - in my case it's with an existing install of openvas

`Error: Transaction check error:
  file /usr/bin/openvas-nasl conflicts between attempted installs of openvas-scanner-6.0.0-6872.el7.art.x86_64 and openvas-libraries-9.0.3-6672.el7.art.x86_64
  file /usr/bin/openvas-nasl-lint conflicts between attempted installs of openvas-scanner-6.0.0-6872.el7.art.x86_64 and openvas-libraries-9.0.3-6672.el7.art.x86_64
  file /usr/lib64/libopenvas_misc.so conflicts between attempted installs of openvas-scanner-6.0.0-6872.el7.art.x86_64 and openvas-libraries-9.0.3-6672.el7.art.x86_64
  file /usr/lib64/libopenvas_nasl.so conflicts between attempted installs of openvas-scanner-6.0.0-6872.el7.art.x86_64 and openvas-libraries-9.0.3-6672.el7.art.x86_64
  file /usr/share/man/man1/openvas-nasl.1.gz conflicts between attempted installs of openvas-scanner-6.0.0-6872.el7.art.x86_64 and openvas-libraries-9.0.3-6672.el7.art.x86_64`

**Comment by atomicturtle** [comment]
gvmd has been updated to address this issue, thanks for the report!
